Пишет 2 функции
htmlacademy-javascript/1573711-keksobooking-27 pull request #2
Opened 2022-10-01 08:40 UTC by loonymax

2022-10-02 09:31 UTC, Pakistanka requested changes

2022-10-02 09:31 UTC, Pakistanka commented on js/main.js
> +    return NaN;
Для наглядности, могу предложить добавить alert `alert('There is no correct value')`, чтобы тебе было легче, если вдруг функция заходит именно сюда.
Его нужно добавлять до return

2022-10-02 09:31 UTC, Pakistanka commented on js/main.js
> +  return Math.floor(Math.random() * (max - min + 1)) + min;
Лучше возвращать одно значение (как у тебя ниже написано), а не математическое выражение.

Математическое выражение лучше положить в переменную. `const result = Math.floor(Math.random() * (max - min + 1)) + min; return result;`

2022-10-05 11:46 UTC, loonymax commented on js/main.js
> +  return Math.floor(Math.random() * (max - min + 1)) + min;
Сделала

2022-10-05 11:46 UTC, loonymax commented on js/main.js
> +    return NaN;
http://joxi.ru/zANKNR8f1Dak7r
Выдает ошибку :( Я что-то не так пишу?

2022-10-05 16:58 UTC, loonymax commented on js/main.js
> +    return NaN;
Если я правильно понимаю, ругается линтер на alert, да?

2022-10-06 11:09 UTC, Pakistanka commented on js/main.js
> +    return NaN;
Да, alert и console.log нельзя использовать

2022-10-07 07:16 UTC, merged